// Clés des illustrations aquarelle (apps/web/src/components/illustrations). Chaque recette en choisit une : son produit vedette.
export const ILLUSTRATION_KEYS = [
  "courge",
  "potiron",
  "carotte",
  "poireau",
  "chou",
  "chou-fleur",
  "brocoli",
  "epinard",
  "betterave",
  "panais",
  "patate-douce",
  "champignon",
  "pomme-de-terre",
  "oignon",
  "celeri",
  "navet",
  "poivron",
  "tomate",
  "poire",
  "pomme",
  "raisin",
  "figue",
  "coing",
  "kiwi",
  "clementine",
  "citron",
  "chataigne",
  "lentilles",
  "pois-chiche",
  "poisson",
  "oeuf",
  "avoine",
  "viande",
  "poulet",
  "haricot",
  "tofu",
  "pates",
  "riz",
  "cereales",
  "pain",
] as const;
export type IllustrationKey = (typeof ILLUSTRATION_KEYS)[number];
